### ISSUE TITLE
Glossário dos nomes

### ISSUE THREAD

**Issue by camilo87** [git-na-pratica/git-na-pratica#4]
Olá a todos do projeto,
não sei nem se essa é a área certa para isso, mas queria pedir se vocês poderiam criar um glossário com uma pequena descrição de cada nome (branch master, commit, e os outros).

Sou designer, tenho conhecimento nulos sobre linhas de comando, mas estou querendo aprender a usar o github e mais ou menos no meio dos ítens acabei me confundindo com algumas terminologias. Entendo o que o texto está dizendo, mas por não conhecer os nomes fico sem saber o sentido. Parece idiota, mas não entendi mesmo :(

Talvez mais algumas pessoas tenham a mesma dúvida e se vocês pudessem esclarecer isso seria legal demais.
De qualquer forma, parabéns pela iniciativa. Pelo menos a mim já ajudou bastante.

obrigado
Camilo

**Comment by carlosdelfino** [comment]
Olá Camilo, estou retomando o projeto, estarei criando o glossário esta semana, e qual dúvida é só nos enviar.

E sim este é o melhor lugar para postar dúvidas e sugestões.
